export type { Product } from "@/types/product";
import type { Product } from "@/types/product";

export const categories = [
  { id: "1", name: "Organic Dals", slug: "organic-dals", icon: "🌾", count: 8, description: "Hand-picked mountain lentils", image: "https://images.unsplash.com/photo-1601000938259-4a3e47d9aa5f?w=400" },
  { id: "2", name: "Dry Fruits & Nuts", slug: "dry-fruits", icon: "🥜", count: 12, description: "Himalayan dry fruits & nuts", image: "https://images.unsplash.com/photo-1596591868231-05e808fd131d?w=400" },
  { id: "3", name: "Fresh Apples", slug: "apples", icon: "🍎", count: 5, description: "Crisp Himachali apples", image: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400" },
  { id: "4", name: "Pure Honey", slug: "honey", icon: "🍯", count: 4, description: "Raw mountain honey", image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400" },
  { id: "5", name: "Himachali Shawls", slug: "shawls", icon: "🧣", count: 10, description: "Traditional woolen shawls", image: "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=400" },
  { id: "6", name: "Himachali Topi", slug: "topi", icon: "🧢", count: 6, description: "Traditional Himachali caps", image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400" },
  { id: "7", name: "Pattu", slug: "pattu", icon: "🧵", count: 7, description: "Handwoven woolen fabric", image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400" },
  { id: "8", name: "Pahadi Spices", slug: "spices", icon: "🌶️", count: 9, description: "Aromatic mountain spices", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Organic Himachali Rajma",
    slug: "organic-himachali-rajma",
    category: "Organic Dals",
    categorySlug: "organic-dals",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.8,
    reviews: 128,
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1601000938259-4a3e47d9aa5f?w=600",
      "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600",
      "https://images.unsplash.com/photo-1585996600000-cb7e2a0b60cb?w=600",
    ],
    description: "Hand-picked organic Rajma (kidney beans) from the pristine valleys of Bharmour, Himachal Pradesh. Grown at an altitude of 2,000+ meters without any pesticides or chemicals. These Rajma have a unique earthy flavor and creamy texture that makes them ideal for the classic Rajma Chawal dish.",
    shortDescription: "Premium mountain-grown kidney beans from Bharmour's organic farms.",
    features: ["100% Organic", "No Pesticides", "High Protein", "Rich in Iron", "Mountain grown at 2000m+"],
    weight: "500g",
    origin: "Bharmour, Himachal Pradesh",
    badge: "bestseller",
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: "2",
    name: "Black Maah Dal (Urad)",
    slug: "black-maah-dal",
    category: "Organic Dals",
    categorySlug: "organic-dals",
    price: 249,
    originalPrice: 320,
    discount: 22,
    rating: 4.7,
    reviews: 95,
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600",
      "https://images.unsplash.com/photo-1601000938259-4a3e47d9aa5f?w=600",
    ],
    description: "Traditional Black Maah Dal from the high-altitude farms of Himachal Pradesh. Known for its rich, buttery taste and exceptional nutritional value. Perfect for making Dal Makhani.",
    shortDescription: "Traditional Himachali Black Urad Dal, organically grown.",
    features: ["Heirloom variety", "Organic certified", "High protein", "Traditional farming"],
    weight: "500g",
    origin: "Chamba, Himachal Pradesh",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "3",
    name: "Himalayan Wild Honey",
    slug: "himalayan-wild-honey",
    category: "Pure Honey",
    categorySlug: "honey",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviews: 204,
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600",
      "https://images.unsplash.com/photo-1471943038374-5b0b5f0ee3c1?w=600",
    ],
    description: "Raw, unprocessed wild honey collected from the high-altitude meadows of Bharmour. The bees feed on wildflowers including rhododendron and deodar blossoms, giving this honey its distinctive floral aroma and complex flavor profile.",
    shortDescription: "Raw, unfiltered honey from Himalayan wildflower meadows.",
    features: ["100% Raw", "Unprocessed", "Wildflower nectar", "No additives", "Medicinal properties"],
    weight: "500g",
    origin: "Bharmour, Himachal Pradesh",
    badge: "premium",
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: "4",
    name: "Himachali Kullu Shawl",
    slug: "kullu-shawl",
    category: "Himachali Shawls",
    categorySlug: "shawls",
    price: 2499,
    originalPrice: 3500,
    discount: 29,
    rating: 4.8,
    reviews: 67,
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=600",
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600",
    ],
    description: "Authentic Kullu Shawl handwoven by local Himachali artisans using traditional loom techniques passed down through generations. Made from premium Merino wool with intricate geometric patterns inspired by Himachali folk art.",
    shortDescription: "Handwoven traditional shawl by Himachali artisans.",
    features: ["100% Merino wool", "Handwoven", "Traditional patterns", "Warm & soft", "Artisan crafted"],
    origin: "Kullu, Himachal Pradesh",
    badge: "handmade",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "5",
    name: "Kashmiri Walnuts (Akhrot)",
    slug: "himalayan-walnuts",
    category: "Dry Fruits & Nuts",
    categorySlug: "dry-fruits",
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 4.6,
    reviews: 145,
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1596591868231-05e808fd131d?w=600",
      "https://images.unsplash.com/photo-1604270050809-fd0ce99e5f3a?w=600",
    ],
    description: "Premium paper-shell walnuts from the Himalayan orchards. Hand-cracked and carefully selected to ensure only the finest, plump kernels reach you. Rich in Omega-3 fatty acids and antioxidants.",
    shortDescription: "Premium paper-shell Himalayan walnuts, rich in Omega-3.",
    features: ["Paper-shell variety", "Hand-cracked", "Rich in Omega-3", "No preservatives"],
    weight: "500g",
    origin: "Kinnaur, Himachal Pradesh",
    isFeatured: true,
  },
  {
    id: "6",
    name: "Himachali Topi (Traditional Cap)",
    slug: "himachali-topi",
    category: "Himachali Topi",
    categorySlug: "topi",
    price: 799,
    originalPrice: 1100,
    discount: 27,
    rating: 4.7,
    reviews: 89,
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600",
      "https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=600",
    ],
    description: "Authentic Himachali Topi handcrafted by traditional artisans from Bharmour. Made with premium wool and adorned with traditional embroidery. A symbol of Himachali identity and pride.",
    shortDescription: "Traditional Himachali cap with authentic embroidery.",
    features: ["Premium wool", "Handcrafted", "Traditional embroidery", "Authentic design", "Cultural heritage"],
    origin: "Bharmour, Himachal Pradesh",
    badge: "handmade",
    isFeatured: true,
  },
  {
    id: "7",
    name: "Himachali Red Apple Box",
    slug: "himachali-red-apples",
    category: "Fresh Apples",
    categorySlug: "apples",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    rating: 4.9,
    reviews: 312,
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600",
      "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600",
    ],
    description: "Fresh, crisp Royal Delicious apples from the high-altitude orchards of Himachal Pradesh. Packed with care in an eco-friendly box. These apples are naturally sweet with a perfect crunch.",
    shortDescription: "Fresh Royal Delicious apples from Himachali high-altitude orchards.",
    features: ["Farm-fresh", "High-altitude grown", "Naturally sweet", "Eco-friendly packaging"],
    weight: "5 kg Box",
    origin: "Shimla, Himachal Pradesh",
    badge: "seasonal",
    isFeatured: true,
    isBestseller: true,
  },
  {
    id: "8",
    name: "Pattu Woolen Fabric",
    slug: "pattu-woolen-fabric",
    category: "Pattu",
    categorySlug: "pattu",
    price: 1899,
    originalPrice: 2500,
    discount: 24,
    rating: 4.6,
    reviews: 43,
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600",
      "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=600",
    ],
    description: "Traditional Himachali Pattu, a hand-woven woolen fabric that forms the base for traditional dresses. Made by skilled weavers in the Chamba district using age-old techniques.",
    shortDescription: "Handwoven traditional Himachali Pattu fabric by local weavers.",
    features: ["100% Wool", "Handwoven", "Traditional pattern", "Durable", "Heritage craft"],
    origin: "Chamba, Himachal Pradesh",
    badge: "heritage",
    isNew: true,
  },
  {
    id: "9",
    name: "Mixed Himalayan Dry Fruits",
    slug: "mixed-himalayan-dry-fruits",
    category: "Dry Fruits & Nuts",
    categorySlug: "dry-fruits",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    rating: 4.7,
    reviews: 178,
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1604270050809-fd0ce99e5f3a?w=600",
      "https://images.unsplash.com/photo-1596591868231-05e808fd131d?w=600",
    ],
    description: "A premium gift box of assorted Himalayan dry fruits including walnuts, almonds, cashews, raisins, and apricots. Sourced directly from mountain orchards and farms.",
    shortDescription: "Premium assorted dry fruits gift box from Himalayan orchards.",
    features: ["Assorted variety", "Gift ready", "No artificial flavors", "Mountain sourced"],
    weight: "750g",
    origin: "Various, Himachal Pradesh",
    badge: "gift",
    isBestseller: true,
  },
  {
    id: "10",
    name: "Himachali Pahadi Masala",
    slug: "pahadi-masala",
    category: "Pahadi Spices",
    categorySlug: "spices",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.5,
    reviews: 234,
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600",
      "https://images.unsplash.com/photo-1599909631453-41e98e2c3c94?w=600",
    ],
    description: "Authentic Pahadi Masala blend with wild herbs and spices from the Himalayan forests. A secret recipe passed down through Himachali households for generations.",
    shortDescription: "Traditional Himachali spice blend with wild mountain herbs.",
    features: ["Wild herbs", "Traditional recipe", "No preservatives", "Authentic flavor"],
    weight: "100g",
    origin: "Bharmour, Himachal Pradesh",
    isBestseller: true,
  },
  {
    id: "11",
    name: "Chamba Chukh (Spicy Citrus Preserve)",
    slug: "chamba-chukh",
    category: "Pahadi Spices",
    categorySlug: "spices",
    price: 299,
    originalPrice: 380,
    discount: 21,
    rating: 4.8,
    reviews: 156,
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1599909631453-41e98e2c3c94?w=600",
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600",
    ],
    description: "Chamba Chukh is a traditional Himachali condiment made from dried citrus rinds and fiery local chillies. A bold, tangy, and spicy paste that transforms any dish.",
    shortDescription: "Traditional Himachali chilli-citrus condiment from Chamba.",
    features: ["Traditional recipe", "Fiery & tangy", "No artificial color", "Authentic taste"],
    weight: "200g",
    origin: "Chamba, Himachal Pradesh",
    badge: "traditional",
    isNew: true,
  },
  {
    id: "12",
    name: "Himalayan Almonds (Badam)",
    slug: "himalayan-almonds",
    category: "Dry Fruits & Nuts",
    categorySlug: "dry-fruits",
    price: 899,
    originalPrice: 1199,
    discount: 25,
    rating: 4.7,
    reviews: 198,
    stock: 55,
    images: [
      "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600",
      "https://images.unsplash.com/photo-1596591868231-05e808fd131d?w=600",
    ],
    description: "Premium gurbandi almonds from the high-altitude Kinnaur orchards. Smaller and more nutritious than regular almonds, these are known for their intense flavor and superior health benefits.",
    shortDescription: "Premium Kinnauri gurbandi almonds from high-altitude orchards.",
    features: ["Gurbandi variety", "High-altitude grown", "Rich in Vitamin E", "Superior flavor"],
    weight: "500g",
    origin: "Kinnaur, Himachal Pradesh",
    isBestseller: true,
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Priya Sharma",
    location: "Delhi",
    rating: 5,
    comment: "The Rajma from BharmouriRoots is absolutely exceptional! It tastes just like my grandmother used to make. The quality is unmatched and delivery was perfectly packaged.",
    avatar: "https://i.pravatar.cc/100?img=1",
    product: "Organic Himachali Rajma",
    date: "2 weeks ago",
  },
  {
    id: "2",
    name: "Rahul Verma",
    location: "Mumbai",
    rating: 5,
    comment: "Got the Kullu Shawl as a gift and it's stunning! The craftsmanship is beautiful and it keeps me so warm. Worth every rupee. Will definitely order more.",
    avatar: "https://i.pravatar.cc/100?img=7",
    product: "Kullu Shawl",
    date: "1 month ago",
  },
  {
    id: "3",
    name: "Anita Kapoor",
    location: "Bangalore",
    rating: 5,
    comment: "The wild honey is pure liquid gold! I can taste the difference from store-bought immediately. It has this beautiful floral taste that is just divine.",
    avatar: "https://i.pravatar.cc/100?img=5",
    product: "Himalayan Wild Honey",
    date: "3 weeks ago",
  },
  {
    id: "4",
    name: "Vikram Singh",
    location: "Chandigarh",
    rating: 5,
    comment: "Being from Himachal myself, I know authenticity. BharmouriRoots delivers exactly that. The Himachali Topi I ordered is perfect. My parents loved it!",
    avatar: "https://i.pravatar.cc/100?img=12",
    product: "Himachali Topi",
    date: "5 days ago",
  },
  {
    id: "5",
    name: "Sunita Mehta",
    location: "Pune",
    rating: 5,
    comment: "The apple box arrived so fresh! You can taste the difference between these mountain apples and what we get locally. Already placed my second order.",
    avatar: "https://i.pravatar.cc/100?img=9",
    product: "Himachali Red Apple Box",
    date: "1 week ago",
  },
  {
    id: "6",
    name: "Arun Sharma",
    location: "Hyderabad",
    rating: 4,
    comment: "Great quality dry fruits. The mixed box is excellent value for money. Gift-worthy packaging and everything tasted fresh. Highly recommend!",
    avatar: "https://i.pravatar.cc/100?img=15",
    product: "Mixed Himalayan Dry Fruits",
    date: "2 months ago",
  },
];

export const heroSlides = [
  {
    id: 1,
    title: "From the Heart of the Himalayas",
    subtitle: "Pure, Organic & Handcrafted",
    description: "Experience the authentic taste of Bharmour's organic farms and the artistry of Himachali craftsmen, delivered to your doorstep.",
    cta: "Shop Now",
    ctaLink: "/products",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600",
    badge: "100% Organic & Authentic",
  },
  {
    id: 2,
    title: "Himachali Heritage in Every Thread",
    subtitle: "Traditional Handwoven Shawls & Topi",
    description: "Carry the warmth of the mountains. Each shawl tells a story of Himachali culture woven by skilled artisans.",
    cta: "Explore Crafts",
    ctaLink: "/products?category=shawls",
    image: "https://images.unsplash.com/photo-1601924638867-3a6de6b7a500?w=1600",
    badge: "Handcrafted with Love",
  },
  {
    id: 3,
    title: "Nature's Sweetest Gift",
    subtitle: "Raw Himalayan Wild Honey",
    description: "Harvested from high-altitude meadows where wildflowers bloom. Pure, unprocessed, and full of nature's goodness.",
    cta: "Shop Honey",
    ctaLink: "/products?category=honey",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=1600",
    badge: "Raw & Unprocessed",
  },
];

export const mockOrders = [
  {
    id: "ORD-2024-001",
    date: "2024-12-01",
    status: "delivered",
    total: 1598,
    items: [{ product: products[0], quantity: 2 }, { product: products[2], quantity: 1 }],
  },
  {
    id: "ORD-2024-002",
    date: "2024-12-10",
    status: "processing",
    total: 2499,
    items: [{ product: products[3], quantity: 1 }],
  },
  {
    id: "ORD-2024-003",
    date: "2024-12-15",
    status: "shipped",
    total: 999,
    items: [{ product: products[6], quantity: 1 }],
  },
];

export const faqs = [
  {
    question: "Are all your products genuinely organic?",
    answer: "Yes, absolutely. All our agricultural products are grown without any pesticides or synthetic fertilizers by local farmers in Himachal Pradesh. We personally visit farms to verify quality.",
  },
  {
    question: "How long does delivery take?",
    answer: "We typically deliver within 5-7 business days across India. For perishable items like apples and honey, we use expedited shipping to ensure freshness.",
  },
  {
    question: "Can I return a product if I'm not satisfied?",
    answer: "Yes, we have a 7-day return policy for all non-perishable items. For quality issues, we offer full replacements or refunds with no questions asked.",
  },
  {
    question: "Do you ship internationally?",
    answer: "Currently we ship within India only. We're working on international shipping and hope to launch it soon. You can join our waitlist.",
  },
  {
    question: "How do you ensure the authenticity of handmade products?",
    answer: "We work directly with verified artisan communities in Kullu, Chamba, and Bharmour. Each product comes with a certificate of authenticity and the maker's story.",
  },
  {
    question: "Do you offer bulk/corporate orders?",
    answer: "Yes! We offer special pricing for bulk and corporate gifting orders. Contact us at tester.net5@gmail.com or use our contact form for bulk order inquiries.",
  },
];
